### ISSUE TITLE
Typo - AmazonS3Write Function 

### ISSUE THREAD

**Issue by AaronJWhite** [OpenBD/openbd-manual#2]
The description for the _aes256key_ argument of AmazonS3Write states to use the function GenerateSecurityKey('aes', 256) to generate an AES 256 key. Unless that's an undocumented alias the function that is really needed is **GenerateSecretKey()**.

**Comment by wua22** [comment]
This has been fixed in this commit to openbd-core

https://github.com/OpenBD/openbd-core/commit/cf55e9971c5f1137e696b06203fc8786c1f40e15
